<?php

$afusertypes = [
	'cosplay-female'			=> 'Cosplayer - Female Characters',
	'cosplay-male'				=> 'Cosplayer - Male Characters',
	'cosplay-other'				=> 'Cosplayer - Other',

	'photo-event'				=> 'Photographer - Event Coverage',
	'photo-shoot'				=> 'Photographer - Photo Shoots',

	'video-coverage'			=> 'Videographer - Event Coverage',
	'video-interview'			=> 'Videographer - Interviews',
	'video-music'				=> 'Videographer - Music Videos',

	'commission-general'		=> 'Commissioner - General',
	'commission-accessories'	=> 'Commissioner - Accessories',
	'commission-armor'			=> 'Commissioner - Armor',
	'commission-casting'		=> 'Commissioner - Castings',
	'commission-props'			=> 'Commissioner - Props',
	'commission-seamstress'		=> 'Commissioner - Seamstress',
	'commission-wig'			=> 'Commissioner - Wigs',

	'lolita'					=> 'Lolita Fashion',
	'steampunk'					=> 'Steampunk',
	'mua'						=> 'Makeup Artist',
	'vendor'					=> 'Vendor',

	'artist-alley'				=> 'Artist Alley',
	'con-staff'					=> 'Staff',
	'panelist'					=> 'Panelist',
];
